import {test,expect} from './fixtures.js';
test('notebook saves original and changed outcomes, compares them, and forks safely',async({page})=>{
 await page.goto('./');await expect(page.locator('#play')).toBeEnabled();await page.locator('#sandbox').click();await page.locator('#launch').click();await page.locator('#notebook').click();await page.locator('#checkpoint-name').fill('Original');await page.locator('#save-checkpoint').click();await expect(page.locator('.notebook-entry')).toHaveCount(1);await page.locator('#close-notebook').click();
 await page.locator('#radius').fill('2');await page.locator('#launch').click();await expect(page.locator('#planet-count')).toHaveText('2');await page.locator('#step').click();await page.locator('#notebook').click();await page.locator('#checkpoint-name').fill('Variation');await page.locator('#save-checkpoint').click();await expect(page.locator('.notebook-entry')).toHaveCount(2);
 await page.getByRole('checkbox',{name:'Compare Original',exact:true}).check();await page.getByRole('checkbox',{name:'Compare Variation',exact:true}).check();await expect(page.locator('#comparison')).toBeVisible();await expect(page.locator('#comparison tbody tr').filter({has:page.getByRole('rowheader',{name:'Worlds',exact:true})})).toContainText('+1');
 await page.locator('.history-review summary').click();await page.locator('#history-tick').evaluate(input=>{input.value='0';input.dispatchEvent(new Event('change',{bubbles:true}));});await expect(page.locator('#sim-years')).toHaveText('0.00');await expect(page.locator('#history-latest')).toBeEnabled();await page.locator('#history-latest').click();await expect(page.locator('#sim-years')).toHaveText('0.03');
 await page.locator('.notebook-entry').filter({has:page.getByRole('heading',{name:'Original',exact:true})}).getByRole('button',{name:'Open / fork'}).click();await page.locator('#confirm-ok').click();await expect(page.locator('#planet-count')).toHaveText('1');await expect(page.locator('#sim-years')).toHaveText('0.00');
 await page.reload();await expect(page.locator('#play')).toBeEnabled();await page.locator('#notebook').click();await expect(page.locator('.notebook-entry')).toHaveCount(2);
});
