import test from 'node:test';import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';
import init,{Simulation} from '../dist/pkg/celestial_wasm.js';
await init({module_or_path:await readFile('dist/pkg/celestial_wasm_bg.wasm')});
// Captured from deployed a633c3d (rules 6), not regenerated by the current solver.
// The packed physical fields include signed zeros; ledgers and histories follow.
const references=new Map([
 [512,'b0eb78adecb38e65cea5c2117382ff739ca3768ad0541ed25bac8a653709b386'],
 [513,'e660162dfccb2430589d519df9465db46b3feb592f43fe6182f40a814d16caf8'],
 [1024,'4924285093e1215b20990720538e178ea395e54e60b08a5eb33f3b7e15897cc1'],
 [8192,'7e12c48e0db4695bb319fa6e6388fcaa02f3c72a615391a273685efb041561cf'],
]);
test('rules-6 large replays retain the deployed physical trajectory and ledgers',()=>{
 const config={seed:42,mission:null,star_mass:1};
 for(const [count,expected] of references){const s=new Simulation(JSON.stringify(config));try{
  s.import_replay(JSON.stringify({version:6,config,end_tick:32,commands:[{tick:0,command:{type:'seed_swarm',count:count-1,disorder:.8}}]}));
  const frame=s.body_frame(),hash=createHash('sha256').update(new Uint8Array(frame.buffer,frame.byteOffset,frame.byteLength)).update(s.balances()).update(s.observations()).digest('hex');
  assert.equal(hash,expected,`${count} bodies`);
 }finally{s.free();}}
});
